import type { SupportedLocale } from "@/lib/locale";

export type ScreenCopy = {
  viewAll: string;
  contactThemNow: string;
  allClients: string;
  allLocations: string;
  scheduledShift: string;
  currentTime: string;
  scrollFullDay: string;
  scrollFullPeriod: string;
  totalDuration: string;
  rooms: string;
  tasks: string;
  task: string;
  photos: string;
  photo: string;
  clientAndLocation: string;
  client: string;
  location: string;
  startTime: string;
  endTime: string;
  assignedWorkers: string;
  description: string;
  additionalTasks: string;
  photoRequired: string;
  worker: string;
  addTask: string;
  editTask: string;
  saveChanges: string;
  taskName: string;
  enterTaskName: string;
  frequencyType: string;
  durationMin: string;
  duration: string;
  enterDurationMin: string;
  photoInstructions: string;
  photoInstructionsHint: string;
  dailyRandomCount: string;
  requiredPhoto: string;
  remove: string;
  title: string;
  workerInstruction: string;
  workerInstructionPlaceholder: string;
  exampleImageUrl: string;
  addAnotherPhoto: string;
  photoTitlePlaceholder: string;
  daily: string;
  weekly: string;
  monthly: string;
  addRoom: string;
  editRoom: string;
  companyName: string;
  roomName: string;
  enterRoomName: string;
  roomType: string;
  cleaningType: string;
  selectCompany: string;
  selectLocation: string;
  selectCompanyFirst: string;
  selectRoomType: string;
  selectCleaningType: string;
  addLocation: string;
  editLocation: string;
  locationName: string;
  enterLocationName: string;
  type: string;
  selectType: string;
  address: string;
  searchAddress: string;
  gpsPinHint: string;
  locationDescriptionPlaceholder: string;
  managerPhotoReview: string;
  managerPhotoReviewHint: string;
  fromDate: string;
  toDate: string;
  allCleaningPlans: string;
  resetFilters: string;
  reviewStatus: string;
  refresh: string;
  needsMyDecision: string;
  spotChecks: string;
  spotCheck: string;
  notChecked: string;
  passed: string;
  all: string;
  looksGood: string;
  threeRetries: string;
  wrongSubject: string;
  checking: string;
  problemFound: string;
  needsReview: string;
  loadingPhotoReview: string;
  backToPhotoReviews: string;
  photoReviewNotFound: string;
  uploadedPhotos: string;
  shiftDate: string;
  noPhotosUploaded: string;
  approve: string;
  reject: string;
  cancel: string;
  confirmReject: string;
  rejectReason: string;
};

const en: ScreenCopy = {
  viewAll: "View all",
  contactThemNow: "Contact them now or arrange a replacement.",
  allClients: "All clients",
  allLocations: "All locations",
  scheduledShift: "Scheduled shift",
  currentTime: "Current time",
  scrollFullDay: "Scroll horizontally to view the full working day",
  scrollFullPeriod: "Scroll horizontally to compare the full working period.",
  totalDuration: "Total duration",
  rooms: "Rooms",
  tasks: "Tasks",
  task: "task",
  photos: "Photos",
  photo: "Photo",
  clientAndLocation: "Client & location",
  client: "Client",
  location: "Location",
  startTime: "Start time",
  endTime: "End time",
  assignedWorkers: "Assigned workers",
  description: "Description",
  additionalTasks: "Additional tasks",
  photoRequired: "Photo required",
  worker: "Worker",
  addTask: "Add task",
  editTask: "Edit task",
  saveChanges: "Save changes",
  taskName: "Task Name",
  enterTaskName: "Enter task name",
  frequencyType: "Frequency Type",
  durationMin: "Duration (min)",
  duration: "Duration",
  enterDurationMin: "Enter duration (min)",
  photoInstructions: "Photo instructions",
  photoInstructionsHint:
    "Add each photo the worker may be asked to capture. Description and example image are optional.",
  dailyRandomCount: "Daily random count",
  requiredPhoto: "Required photo",
  remove: "Remove",
  title: "Title",
  workerInstruction: "Worker instruction",
  workerInstructionPlaceholder: "Explain what must be visible and where to take the photo from.",
  exampleImageUrl: "Example image URL",
  addAnotherPhoto: "+ Add another photo",
  photoTitlePlaceholder: "e.g. Bathroom after cleaning",
  daily: "Daily",
  weekly: "Weekly",
  monthly: "Monthly",
  addRoom: "Add Room",
  editRoom: "Edit Room",
  companyName: "Company Name",
  roomName: "Room Name",
  enterRoomName: "Enter Room Name",
  roomType: "Room Type",
  cleaningType: "Cleaning Type",
  selectCompany: "Select Company",
  selectLocation: "Select Location",
  selectCompanyFirst: "Select Company first",
  selectRoomType: "Select Room Type",
  selectCleaningType: "Select Cleaning Type",
  addLocation: "Add Location",
  editLocation: "Edit Location",
  locationName: "Location Name",
  enterLocationName: "Enter location name",
  type: "Type",
  selectType: "Select type",
  address: "Address",
  searchAddress: "Search an address",
  gpsPinHint: "Pick a suggestion to save the GPS pin with this location.",
  locationDescriptionPlaceholder: "Anything the cleaning team should know about this location",
  managerPhotoReview: "Manager photo review",
  managerPhotoReviewHint: "Prioritized photos that need a manager check.",
  fromDate: "From date",
  toDate: "To date",
  allCleaningPlans: "All cleaning plans",
  resetFilters: "Reset filters",
  reviewStatus: "Review status",
  refresh: "Refresh",
  needsMyDecision: "Needs my decision",
  spotChecks: "Spot checks",
  spotCheck: "Spot check",
  notChecked: "Not checked",
  passed: "Passed",
  all: "All",
  looksGood: "Looks good",
  threeRetries: "3 retries",
  wrongSubject: "Wrong subject",
  checking: "Checking…",
  problemFound: "Problem found",
  needsReview: "Needs review",
  loadingPhotoReview: "Loading photo review…",
  backToPhotoReviews: "Back to photo reviews",
  photoReviewNotFound: "Photo review not found.",
  uploadedPhotos: "Uploaded photos",
  shiftDate: "Shift date",
  noPhotosUploaded: "No photos uploaded for this task.",
  approve: "Approve",
  reject: "Reject",
  cancel: "Cancel",
  confirmReject: "Confirm reject",
  rejectReason: "Reason for rejection",
};

const nl: ScreenCopy = {
  ...en,
  viewAll: "Alles bekijken",
  contactThemNow: "Neem nu contact op of regel een vervanger.",
  allClients: "Alle klanten",
  allLocations: "Alle locaties",
  scheduledShift: "Geplande dienst",
  currentTime: "Huidige tijd",
  scrollFullDay: "Scroll horizontaal om de hele werkdag te zien",
  scrollFullPeriod: "Scroll horizontaal om de volledige werkperiode te vergelijken.",
  totalDuration: "Totale duur",
  rooms: "Kamers",
  tasks: "Taken",
  task: "taak",
  photos: "Foto's",
  photo: "Foto",
  clientAndLocation: "Klant & locatie",
  client: "Klant",
  location: "Locatie",
  startTime: "Starttijd",
  endTime: "Eindtijd",
  assignedWorkers: "Toegewezen medewerkers",
  description: "Beschrijving",
  additionalTasks: "Extra taken",
  photoRequired: "Foto vereist",
  worker: "Medewerker",
  addTask: "Taak toevoegen",
  editTask: "Taak bewerken",
  saveChanges: "Wijzigingen opslaan",
  taskName: "Taaknaam",
  enterTaskName: "Voer taaknaam in",
  frequencyType: "Frequentietype",
  durationMin: "Duur (min)",
  duration: "Duur",
  enterDurationMin: "Voer duur in (min)",
  photoInstructions: "Foto-instructies",
  photoInstructionsHint:
    "Voeg elke foto toe die de medewerker kan moeten maken. Beschrijving en voorbeeldbeeld zijn optioneel.",
  dailyRandomCount: "Dagelijks willekeurig aantal",
  requiredPhoto: "Vereiste foto",
  remove: "Verwijderen",
  title: "Titel",
  workerInstruction: "Instructie voor medewerker",
  workerInstructionPlaceholder: "Leg uit wat zichtbaar moet zijn en vanaf waar de foto genomen moet worden.",
  exampleImageUrl: "URL van voorbeeldbeeld",
  addAnotherPhoto: "+ Nog een foto toevoegen",
  photoTitlePlaceholder: "bijv. Badkamer na schoonmaak",
  daily: "Dagelijks",
  weekly: "Wekelijks",
  monthly: "Maandelijks",
  addRoom: "Kamer toevoegen",
  editRoom: "Kamer bewerken",
  companyName: "Bedrijfsnaam",
  roomName: "Kamernaam",
  enterRoomName: "Voer kamernaam in",
  roomType: "Kamertype",
  cleaningType: "Schoonmaaktype",
  selectCompany: "Selecteer bedrijf",
  selectLocation: "Selecteer locatie",
  selectCompanyFirst: "Selecteer eerst een bedrijf",
  selectRoomType: "Selecteer kamertype",
  selectCleaningType: "Selecteer schoonmaaktype",
  addLocation: "Locatie toevoegen",
  editLocation: "Locatie bewerken",
  locationName: "Locatienaam",
  enterLocationName: "Voer locatienaam in",
  type: "Type",
  selectType: "Selecteer type",
  address: "Adres",
  searchAddress: "Zoek een adres",
  gpsPinHint: "Kies een suggestie om de GPS-pin bij deze locatie op te slaan.",
  locationDescriptionPlaceholder: "Alles wat het schoonmaakteam over deze locatie moet weten",
  managerPhotoReview: "Fotobeoordeling door manager",
  managerPhotoReviewHint: "Geprioriteerde foto's die een managercontrole nodig hebben.",
  fromDate: "Vanaf datum",
  toDate: "Tot datum",
  allCleaningPlans: "Alle schoonmaakplannen",
  resetFilters: "Filters resetten",
  reviewStatus: "Beoordelingsstatus",
  refresh: "Vernieuwen",
  needsMyDecision: "Mijn beslissing nodig",
  spotChecks: "Steekproeven",
  spotCheck: "Steekproef",
  notChecked: "Niet gecontroleerd",
  passed: "Geslaagd",
  all: "Alles",
  looksGood: "Ziet er goed uit",
  threeRetries: "3 pogingen",
  wrongSubject: "Verkeerd onderwerp",
  checking: "Controleren…",
  problemFound: "Probleem gevonden",
  needsReview: "Beoordeling nodig",
  loadingPhotoReview: "Fotobeoordeling laden…",
  backToPhotoReviews: "Terug naar fotobeoordelingen",
  photoReviewNotFound: "Fotobeoordeling niet gevonden.",
  uploadedPhotos: "Geüploade foto's",
  shiftDate: "Dienstdatum",
  noPhotosUploaded: "Geen foto's geüpload voor deze taak.",
  approve: "Goedkeuren",
  reject: "Afwijzen",
  cancel: "Annuleren",
  confirmReject: "Afwijzing bevestigen",
  rejectReason: "Reden voor afwijzing",
};

const fr: ScreenCopy = {
  ...en,
  viewAll: "Tout voir",
  contactThemNow: "Contactez-les maintenant ou prévoyez un remplacement.",
  allClients: "Tous les clients",
  allLocations: "Tous les sites",
  scheduledShift: "Vacation planifiée",
  currentTime: "Heure actuelle",
  scrollFullDay: "Faites défiler horizontalement pour voir toute la journée",
  scrollFullPeriod: "Faites défiler horizontalement pour comparer toute la période de travail.",
  totalDuration: "Durée totale",
  rooms: "Pièces",
  tasks: "Tâches",
  task: "tâche",
  photos: "Photos",
  photo: "Photo",
  clientAndLocation: "Client et site",
  client: "Client",
  location: "Site",
  startTime: "Heure de début",
  endTime: "Heure de fin",
  assignedWorkers: "Employés assignés",
  description: "Description",
  additionalTasks: "Tâches supplémentaires",
  photoRequired: "Photo requise",
  worker: "Employé",
  addTask: "Ajouter une tâche",
  editTask: "Modifier la tâche",
  saveChanges: "Enregistrer",
  taskName: "Nom de la tâche",
  enterTaskName: "Saisir le nom de la tâche",
  frequencyType: "Type de fréquence",
  durationMin: "Durée (min)",
  duration: "Durée",
  enterDurationMin: "Saisir la durée (min)",
  photoInstructions: "Instructions photo",
  photoInstructionsHint:
    "Ajoutez chaque photo que l’employé pourra devoir prendre. La description et l’image d’exemple sont facultatives.",
  dailyRandomCount: "Nombre aléatoire quotidien",
  requiredPhoto: "Photo requise",
  remove: "Supprimer",
  title: "Titre",
  workerInstruction: "Instruction pour l’employé",
  workerInstructionPlaceholder: "Expliquez ce qui doit être visible et d’où prendre la photo.",
  exampleImageUrl: "URL de l’image d’exemple",
  addAnotherPhoto: "+ Ajouter une autre photo",
  photoTitlePlaceholder: "ex. Salle de bain après nettoyage",
  daily: "Quotidien",
  weekly: "Hebdomadaire",
  monthly: "Mensuel",
  addRoom: "Ajouter une pièce",
  editRoom: "Modifier la pièce",
  companyName: "Nom de l’entreprise",
  roomName: "Nom de la pièce",
  enterRoomName: "Saisir le nom de la pièce",
  roomType: "Type de pièce",
  cleaningType: "Type de nettoyage",
  selectCompany: "Sélectionner l’entreprise",
  selectLocation: "Sélectionner le site",
  selectCompanyFirst: "Sélectionnez d’abord une entreprise",
  selectRoomType: "Sélectionner le type de pièce",
  selectCleaningType: "Sélectionner le type de nettoyage",
  addLocation: "Ajouter un site",
  editLocation: "Modifier le site",
  locationName: "Nom du site",
  enterLocationName: "Saisir le nom du site",
  type: "Type",
  selectType: "Sélectionner le type",
  address: "Adresse",
  searchAddress: "Rechercher une adresse",
  gpsPinHint: "Choisissez une suggestion pour enregistrer l’épingle GPS de ce site.",
  locationDescriptionPlaceholder: "Tout ce que l’équipe de nettoyage doit savoir sur ce site",
  managerPhotoReview: "Revue photo du manager",
  managerPhotoReviewHint: "Photos prioritaires nécessitant une vérification du manager.",
  fromDate: "Date de début",
  toDate: "Date de fin",
  allCleaningPlans: "Tous les plans de nettoyage",
  resetFilters: "Réinitialiser les filtres",
  reviewStatus: "Statut de la revue",
  refresh: "Actualiser",
  needsMyDecision: "Ma décision est requise",
  spotChecks: "Contrôles ponctuels",
  spotCheck: "Contrôle ponctuel",
  notChecked: "Non vérifié",
  passed: "Validé",
  all: "Tout",
  looksGood: "Correct",
  threeRetries: "3 tentatives",
  wrongSubject: "Mauvais sujet",
  checking: "Vérification…",
  problemFound: "Problème détecté",
  needsReview: "Revue nécessaire",
  loadingPhotoReview: "Chargement de la revue photo…",
  backToPhotoReviews: "Retour aux revues photo",
  photoReviewNotFound: "Revue photo introuvable.",
  uploadedPhotos: "Photos téléchargées",
  shiftDate: "Date de vacation",
  noPhotosUploaded: "Aucune photo téléchargée pour cette tâche.",
  approve: "Approuver",
  reject: "Refuser",
  cancel: "Annuler",
  confirmReject: "Confirmer le refus",
  rejectReason: "Motif du refus",
};

const es: ScreenCopy = {
  ...en,
  viewAll: "Ver todo",
  contactThemNow: "Contáctelos ahora o gestione un reemplazo.",
  allClients: "Todos los clientes",
  allLocations: "Todas las ubicaciones",
  scheduledShift: "Turno programado",
  currentTime: "Hora actual",
  scrollFullDay: "Desplace horizontalmente para ver toda la jornada",
  scrollFullPeriod: "Desplace horizontalmente para comparar todo el periodo de trabajo.",
  totalDuration: "Duración total",
  rooms: "Habitaciones",
  tasks: "Tareas",
  task: "tarea",
  photos: "Fotos",
  photo: "Foto",
  clientAndLocation: "Cliente y ubicación",
  client: "Cliente",
  location: "Ubicación",
  startTime: "Hora de inicio",
  endTime: "Hora de fin",
  assignedWorkers: "Trabajadores asignados",
  description: "Descripción",
  additionalTasks: "Tareas adicionales",
  photoRequired: "Foto obligatoria",
  worker: "Trabajador",
  addTask: "Añadir tarea",
  editTask: "Editar tarea",
  saveChanges: "Guardar cambios",
  taskName: "Nombre de la tarea",
  enterTaskName: "Introducir nombre de la tarea",
  frequencyType: "Tipo de frecuencia",
  durationMin: "Duración (min)",
  duration: "Duración",
  enterDurationMin: "Introducir duración (min)",
  photoInstructions: "Instrucciones de foto",
  photoInstructionsHint:
    "Añada cada foto que el trabajador pueda tener que capturar. La descripción y la imagen de ejemplo son opcionales.",
  dailyRandomCount: "Recuento aleatorio diario",
  requiredPhoto: "Foto requerida",
  remove: "Eliminar",
  title: "Título",
  workerInstruction: "Instrucción para el trabajador",
  workerInstructionPlaceholder: "Explique qué debe verse y desde dónde tomar la foto.",
  exampleImageUrl: "URL de imagen de ejemplo",
  addAnotherPhoto: "+ Añadir otra foto",
  photoTitlePlaceholder: "ej. Baño después de limpiar",
  daily: "Diario",
  weekly: "Semanal",
  monthly: "Mensual",
  addRoom: "Añadir habitación",
  editRoom: "Editar habitación",
  companyName: "Nombre de la empresa",
  roomName: "Nombre de la habitación",
  enterRoomName: "Introducir nombre de la habitación",
  roomType: "Tipo de habitación",
  cleaningType: "Tipo de limpieza",
  selectCompany: "Seleccionar empresa",
  selectLocation: "Seleccionar ubicación",
  selectCompanyFirst: "Seleccione primero una empresa",
  selectRoomType: "Seleccionar tipo de habitación",
  selectCleaningType: "Seleccionar tipo de limpieza",
  addLocation: "Añadir ubicación",
  editLocation: "Editar ubicación",
  locationName: "Nombre de la ubicación",
  enterLocationName: "Introducir nombre de la ubicación",
  type: "Tipo",
  selectType: "Seleccionar tipo",
  address: "Dirección",
  searchAddress: "Buscar una dirección",
  gpsPinHint: "Elija una sugerencia para guardar el pin GPS de esta ubicación.",
  locationDescriptionPlaceholder: "Todo lo que el equipo de limpieza debe saber sobre esta ubicación",
  managerPhotoReview: "Revisión de fotos del gerente",
  managerPhotoReviewHint: "Fotos priorizadas que necesitan revisión del gerente.",
  fromDate: "Desde la fecha",
  toDate: "Hasta la fecha",
  allCleaningPlans: "Todos los planes de limpieza",
  resetFilters: "Restablecer filtros",
  reviewStatus: "Estado de revisión",
  refresh: "Actualizar",
  needsMyDecision: "Necesita mi decisión",
  spotChecks: "Controles aleatorios",
  spotCheck: "Control aleatorio",
  notChecked: "Sin revisar",
  passed: "Aprobado",
  all: "Todo",
  looksGood: "Correcto",
  threeRetries: "3 intentos",
  wrongSubject: "Tema incorrecto",
  checking: "Comprobando…",
  problemFound: "Problema encontrado",
  needsReview: "Necesita revisión",
  loadingPhotoReview: "Cargando revisión de foto…",
  backToPhotoReviews: "Volver a revisiones de fotos",
  photoReviewNotFound: "No se encontró la revisión de foto.",
  uploadedPhotos: "Fotos subidas",
  shiftDate: "Fecha del turno",
  noPhotosUploaded: "No hay fotos subidas para esta tarea.",
  approve: "Aprobar",
  reject: "Rechazar",
  cancel: "Cancelar",
  confirmReject: "Confirmar rechazo",
  rejectReason: "Motivo del rechazo",
};

const pl: ScreenCopy = {
  ...en,
  viewAll: "Zobacz wszystko",
  contactThemNow: "Skontaktuj się teraz lub zorganizuj zastępstwo.",
  allClients: "Wszyscy klienci",
  allLocations: "Wszystkie lokalizacje",
  scheduledShift: "Zaplanowana zmiana",
  currentTime: "Bieżący czas",
  scrollFullDay: "Przewiń poziomo, aby zobaczyć cały dzień pracy",
  scrollFullPeriod: "Przewiń poziomo, aby porównać cały okres pracy.",
  totalDuration: "Całkowity czas",
  rooms: "Pomieszczenia",
  tasks: "Zadania",
  task: "zadanie",
  photos: "Zdjęcia",
  photo: "Zdjęcie",
  clientAndLocation: "Klient i lokalizacja",
  client: "Klient",
  location: "Lokalizacja",
  startTime: "Godzina rozpoczęcia",
  endTime: "Godzina zakończenia",
  assignedWorkers: "Przypisani pracownicy",
  description: "Opis",
  additionalTasks: "Dodatkowe zadania",
  photoRequired: "Wymagane zdjęcie",
  worker: "Pracownik",
  addTask: "Dodaj zadanie",
  editTask: "Edytuj zadanie",
  saveChanges: "Zapisz zmiany",
  taskName: "Nazwa zadania",
  enterTaskName: "Wpisz nazwę zadania",
  frequencyType: "Typ częstotliwości",
  durationMin: "Czas (min)",
  duration: "Czas trwania",
  enterDurationMin: "Podaj czas (min)",
  photoInstructions: "Instrukcje zdjęć",
  photoInstructionsHint:
    "Dodaj każde zdjęcie, które pracownik może mieć zrobić. Opis i zdjęcie przykładowe są opcjonalne.",
  dailyRandomCount: "Dzienna losowa liczba",
  requiredPhoto: "Wymagane zdjęcie",
  remove: "Usuń",
  title: "Tytuł",
  workerInstruction: "Instrukcja dla pracownika",
  workerInstructionPlaceholder: "Wyjaśnij, co musi być widoczne i skąd zrobić zdjęcie.",
  exampleImageUrl: "URL zdjęcia przykładowego",
  addAnotherPhoto: "+ Dodaj kolejne zdjęcie",
  photoTitlePlaceholder: "np. Łazienka po sprzątaniu",
  daily: "Codziennie",
  weekly: "Tygodniowo",
  monthly: "Miesięcznie",
  addRoom: "Dodaj pomieszczenie",
  editRoom: "Edytuj pomieszczenie",
  companyName: "Nazwa firmy",
  roomName: "Nazwa pomieszczenia",
  enterRoomName: "Wpisz nazwę pomieszczenia",
  roomType: "Typ pomieszczenia",
  cleaningType: "Typ sprzątania",
  selectCompany: "Wybierz firmę",
  selectLocation: "Wybierz lokalizację",
  selectCompanyFirst: "Najpierw wybierz firmę",
  selectRoomType: "Wybierz typ pomieszczenia",
  selectCleaningType: "Wybierz typ sprzątania",
  addLocation: "Dodaj lokalizację",
  editLocation: "Edytuj lokalizację",
  locationName: "Nazwa lokalizacji",
  enterLocationName: "Wpisz nazwę lokalizacji",
  type: "Typ",
  selectType: "Wybierz typ",
  address: "Adres",
  searchAddress: "Wyszukaj adres",
  gpsPinHint: "Wybierz podpowiedź, aby zapisać pinezkę GPS tej lokalizacji.",
  locationDescriptionPlaceholder: "Wszystko, co zespół sprzątający powinien wiedzieć o tej lokalizacji",
  managerPhotoReview: "Weryfikacja zdjęć przez menedżera",
  managerPhotoReviewHint: "Priorytetowe zdjęcia wymagające sprawdzenia przez menedżera.",
  fromDate: "Od daty",
  toDate: "Do daty",
  allCleaningPlans: "Wszystkie plany sprzątania",
  resetFilters: "Resetuj filtry",
  reviewStatus: "Status recenzji",
  refresh: "Odśwież",
  needsMyDecision: "Wymaga mojej decyzji",
  spotChecks: "Kontrole wyrywkowe",
  spotCheck: "Kontrola wyrywkowa",
  notChecked: "Niesprawdzone",
  passed: "Zaliczone",
  all: "Wszystkie",
  looksGood: "Wygląda dobrze",
  threeRetries: "3 próby",
  wrongSubject: "Zły obiekt",
  checking: "Sprawdzanie…",
  problemFound: "Znaleziono problem",
  needsReview: "Wymaga recenzji",
  loadingPhotoReview: "Ładowanie recenzji zdjęcia…",
  backToPhotoReviews: "Wróć do recenzji zdjęć",
  photoReviewNotFound: "Nie znaleziono recenzji zdjęcia.",
  uploadedPhotos: "Przesłane zdjęcia",
  shiftDate: "Data zmiany",
  noPhotosUploaded: "Brak zdjęć dla tego zadania.",
  approve: "Zatwierdź",
  reject: "Odrzuć",
  cancel: "Anuluj",
  confirmReject: "Potwierdź odrzucenie",
  rejectReason: "Powód odrzucenia",
};

const uk: ScreenCopy = {
  ...en,
  viewAll: "Переглянути все",
  contactThemNow: "Зв’яжіться зараз або знайдіть заміну.",
  allClients: "Усі клієнти",
  allLocations: "Усі локації",
  scheduledShift: "Запланована зміна",
  currentTime: "Поточний час",
  scrollFullDay: "Прокрутіть горизонтально, щоб побачити весь робочий день",
  scrollFullPeriod: "Прокрутіть горизонтально, щоб порівняти весь робочий період.",
  totalDuration: "Загальна тривалість",
  rooms: "Кімнати",
  tasks: "Завдання",
  task: "завдання",
  photos: "Фото",
  photo: "Фото",
  clientAndLocation: "Клієнт і локація",
  client: "Клієнт",
  location: "Локація",
  startTime: "Час початку",
  endTime: "Час завершення",
  assignedWorkers: "Призначені працівники",
  description: "Опис",
  additionalTasks: "Додаткові завдання",
  photoRequired: "Потрібне фото",
  worker: "Працівник",
  addTask: "Додати завдання",
  editTask: "Редагувати завдання",
  saveChanges: "Зберегти зміни",
  taskName: "Назва завдання",
  enterTaskName: "Введіть назву завдання",
  frequencyType: "Тип періодичності",
  durationMin: "Тривалість (хв)",
  duration: "Тривалість",
  enterDurationMin: "Вкажіть тривалість (хв)",
  photoInstructions: "Інструкції щодо фото",
  photoInstructionsHint:
    "Додайте кожне фото, яке працівник може мати зробити. Опис і зразок зображення необов’язкові.",
  dailyRandomCount: "Щоденна випадкова кількість",
  requiredPhoto: "Обов’язкове фото",
  remove: "Видалити",
  title: "Назва",
  workerInstruction: "Інструкція для працівника",
  workerInstructionPlaceholder: "Поясніть, що має бути видно і звідки робити фото.",
  exampleImageUrl: "URL зразка зображення",
  addAnotherPhoto: "+ Додати ще фото",
  photoTitlePlaceholder: "напр. Ванна після прибирання",
  daily: "Щоденно",
  weekly: "Щотижня",
  monthly: "Щомісяця",
  addRoom: "Додати кімнату",
  editRoom: "Редагувати кімнату",
  companyName: "Назва компанії",
  roomName: "Назва кімнати",
  enterRoomName: "Введіть назву кімнати",
  roomType: "Тип кімнати",
  cleaningType: "Тип прибирання",
  selectCompany: "Виберіть компанію",
  selectLocation: "Виберіть локацію",
  selectCompanyFirst: "Спочатку виберіть компанію",
  selectRoomType: "Виберіть тип кімнати",
  selectCleaningType: "Виберіть тип прибирання",
  addLocation: "Додати локацію",
  editLocation: "Редагувати локацію",
  locationName: "Назва локації",
  enterLocationName: "Введіть назву локації",
  type: "Тип",
  selectType: "Виберіть тип",
  address: "Адреса",
  searchAddress: "Пошук адреси",
  gpsPinHint: "Оберіть підказку, щоб зберегти GPS-мітку цієї локації.",
  locationDescriptionPlaceholder: "Усе, що команда прибирання має знати про цю локацію",
  managerPhotoReview: "Перевірка фото менеджером",
  managerPhotoReviewHint: "Пріоритетні фото, які потребують перевірки менеджера.",
  fromDate: "Від дати",
  toDate: "До дати",
  allCleaningPlans: "Усі плани прибирання",
  resetFilters: "Скинути фільтри",
  reviewStatus: "Статус перевірки",
  refresh: "Оновити",
  needsMyDecision: "Потрібне моє рішення",
  spotChecks: "Вибіркові перевірки",
  spotCheck: "Вибіркова перевірка",
  notChecked: "Не перевірено",
  passed: "Пройдено",
  all: "Усі",
  looksGood: "Виглядає добре",
  threeRetries: "3 спроби",
  wrongSubject: "Неправильний об’єкт",
  checking: "Перевірка…",
  problemFound: "Знайдено проблему",
  needsReview: "Потрібна перевірка",
  loadingPhotoReview: "Завантаження перевірки фото…",
  backToPhotoReviews: "Назад до перевірок фото",
  photoReviewNotFound: "Перевірку фото не знайдено.",
  uploadedPhotos: "Завантажені фото",
  shiftDate: "Дата зміни",
  noPhotosUploaded: "Для цього завдання немає фото.",
  approve: "Затвердити",
  reject: "Відхилити",
  cancel: "Скасувати",
  confirmReject: "Підтвердити відхилення",
  rejectReason: "Причина відхилення",
};

const pt: ScreenCopy = {
  ...en,
  viewAll: "Ver tudo",
  contactThemNow: "Contacte-os agora ou trate da substituição.",
  allClients: "Todos os clientes",
  allLocations: "Todos os locais",
  scheduledShift: "Turno agendado",
  currentTime: "Hora atual",
  scrollFullDay: "Desloque horizontalmente para ver o dia de trabalho completo",
  scrollFullPeriod: "Desloque horizontalmente para comparar todo o período de trabalho.",
  totalDuration: "Duração total",
  rooms: "Salas",
  tasks: "Tarefas",
  task: "tarefa",
  photos: "Fotos",
  photo: "Foto",
  clientAndLocation: "Cliente e local",
  client: "Cliente",
  location: "Local",
  startTime: "Hora de início",
  endTime: "Hora de fim",
  assignedWorkers: "Trabalhadores atribuídos",
  description: "Descrição",
  additionalTasks: "Tarefas adicionais",
  photoRequired: "Foto obrigatória",
  worker: "Trabalhador",
  addTask: "Adicionar tarefa",
  editTask: "Editar tarefa",
  saveChanges: "Guardar alterações",
  taskName: "Nome da tarefa",
  enterTaskName: "Introduza o nome da tarefa",
  frequencyType: "Tipo de frequência",
  durationMin: "Duração (min)",
  duration: "Duração",
  enterDurationMin: "Indique a duração (min)",
  photoInstructions: "Instruções de foto",
  photoInstructionsHint:
    "Adicione cada foto que o trabalhador possa ter de captar. A descrição e a imagem de exemplo são opcionais.",
  dailyRandomCount: "Contagem aleatória diária",
  requiredPhoto: "Foto obrigatória",
  remove: "Remover",
  title: "Título",
  workerInstruction: "Instrução para o trabalhador",
  workerInstructionPlaceholder: "Explique o que deve estar visível e de onde tirar a foto.",
  exampleImageUrl: "URL da imagem de exemplo",
  addAnotherPhoto: "+ Adicionar outra foto",
  photoTitlePlaceholder: "ex.: Casa de banho após a limpeza",
  daily: "Diário",
  weekly: "Semanal",
  monthly: "Mensal",
  addRoom: "Adicionar sala",
  editRoom: "Editar sala",
  companyName: "Nome da empresa",
  roomName: "Nome da sala",
  enterRoomName: "Introduza o nome da sala",
  roomType: "Tipo de sala",
  cleaningType: "Tipo de limpeza",
  selectCompany: "Selecionar empresa",
  selectLocation: "Selecionar local",
  selectCompanyFirst: "Selecione primeiro uma empresa",
  selectRoomType: "Selecionar tipo de sala",
  selectCleaningType: "Selecionar tipo de limpeza",
  addLocation: "Adicionar local",
  editLocation: "Editar local",
  locationName: "Nome do local",
  enterLocationName: "Introduza o nome do local",
  type: "Tipo",
  selectType: "Selecionar tipo",
  address: "Morada",
  searchAddress: "Pesquisar uma morada",
  gpsPinHint: "Escolha uma sugestão para guardar o pin GPS deste local.",
  locationDescriptionPlaceholder: "Tudo o que a equipa de limpeza deve saber sobre este local",
  managerPhotoReview: "Revisão de fotos do gestor",
  managerPhotoReviewHint: "Fotos priorizadas que precisam de verificação do gestor.",
  fromDate: "Data de início",
  toDate: "Data de fim",
  allCleaningPlans: "Todos os planos de limpeza",
  resetFilters: "Repor filtros",
  reviewStatus: "Estado da revisão",
  refresh: "Atualizar",
  needsMyDecision: "Precisa da minha decisão",
  spotChecks: "Verificações pontuais",
  spotCheck: "Verificação pontual",
  notChecked: "Não verificado",
  passed: "Aprovado",
  all: "Todos",
  looksGood: "Está correto",
  threeRetries: "3 tentativas",
  wrongSubject: "Assunto errado",
  checking: "A verificar…",
  problemFound: "Problema encontrado",
  needsReview: "Precisa de revisão",
  loadingPhotoReview: "A carregar revisão de foto…",
  backToPhotoReviews: "Voltar às revisões de fotos",
  photoReviewNotFound: "Revisão de foto não encontrada.",
  uploadedPhotos: "Fotos carregadas",
  shiftDate: "Data do turno",
  noPhotosUploaded: "Não há fotos carregadas para esta tarefa.",
  approve: "Aprovar",
  reject: "Rejeitar",
  cancel: "Cancelar",
  confirmReject: "Confirmar rejeição",
  rejectReason: "Motivo da rejeição",
};

const ar: ScreenCopy = {
  ...en,
  viewAll: "عرض الكل",
  contactThemNow: "تواصل معهم الآن أو دبّر بديلاً.",
  allClients: "كل العملاء",
  allLocations: "كل المواقع",
  scheduledShift: "وردية مجدولة",
  currentTime: "الوقت الحالي",
  scrollFullDay: "مرّر أفقيًا لعرض يوم العمل بالكامل",
  scrollFullPeriod: "مرّر أفقيًا لمقارنة فترة العمل بالكامل.",
  totalDuration: "المدة الإجمالية",
  rooms: "الغرف",
  tasks: "المهام",
  task: "مهمة",
  photos: "الصور",
  photo: "صورة",
  clientAndLocation: "العميل والموقع",
  client: "العميل",
  location: "الموقع",
  startTime: "وقت البدء",
  endTime: "وقت الانتهاء",
  assignedWorkers: "العاملون المعيَّنون",
  description: "الوصف",
  additionalTasks: "مهام إضافية",
  photoRequired: "صورة مطلوبة",
  worker: "عامل",
  addTask: "إضافة مهمة",
  editTask: "تعديل المهمة",
  saveChanges: "حفظ التغييرات",
  taskName: "اسم المهمة",
  enterTaskName: "أدخل اسم المهمة",
  frequencyType: "نوع التكرار",
  durationMin: "المدة (دقيقة)",
  duration: "المدة",
  enterDurationMin: "أدخل المدة (دقيقة)",
  photoInstructions: "تعليمات الصور",
  photoInstructionsHint: "أضف كل صورة قد يُطلب من العامل التقاطها. الوصف وصورة المثال اختياريان.",
  dailyRandomCount: "العدد العشوائي اليومي",
  requiredPhoto: "الصورة المطلوبة",
  remove: "إزالة",
  title: "العنوان",
  workerInstruction: "تعليمات العامل",
  workerInstructionPlaceholder: "اشرح ما يجب أن يظهر ومن أين تُلتقط الصورة.",
  exampleImageUrl: "رابط صورة المثال",
  addAnotherPhoto: "+ إضافة صورة أخرى",
  photoTitlePlaceholder: "مثال: الحمام بعد التنظيف",
  daily: "يومي",
  weekly: "أسبوعي",
  monthly: "شهري",
  addRoom: "إضافة غرفة",
  editRoom: "تعديل الغرفة",
  companyName: "اسم الشركة",
  roomName: "اسم الغرفة",
  enterRoomName: "أدخل اسم الغرفة",
  roomType: "نوع الغرفة",
  cleaningType: "نوع التنظيف",
  selectCompany: "اختر الشركة",
  selectLocation: "اختر الموقع",
  selectCompanyFirst: "اختر الشركة أولًا",
  selectRoomType: "اختر نوع الغرفة",
  selectCleaningType: "اختر نوع التنظيف",
  addLocation: "إضافة موقع",
  editLocation: "تعديل الموقع",
  locationName: "اسم الموقع",
  enterLocationName: "أدخل اسم الموقع",
  type: "النوع",
  selectType: "اختر النوع",
  address: "العنوان",
  searchAddress: "ابحث عن عنوان",
  gpsPinHint: "اختر اقتراحًا لحفظ دبوس GPS مع هذا الموقع.",
  locationDescriptionPlaceholder: "أي شيء يجب أن يعرفه فريق التنظيف عن هذا الموقع",
  managerPhotoReview: "مراجعة صور المدير",
  managerPhotoReviewHint: "صور ذات أولوية تحتاج إلى فحص المدير.",
  fromDate: "من تاريخ",
  toDate: "إلى تاريخ",
  allCleaningPlans: "كل خطط التنظيف",
  resetFilters: "إعادة تعيين عوامل التصفية",
  reviewStatus: "حالة المراجعة",
  refresh: "تحديث",
  needsMyDecision: "يحتاج قراري",
  spotChecks: "فحوصات عشوائية",
  spotCheck: "فحص عشوائي",
  notChecked: "لم تُفحص",
  passed: "مقبولة",
  all: "الكل",
  looksGood: "تبدو جيدة",
  threeRetries: "3 محاولات",
  wrongSubject: "موضوع خاطئ",
  checking: "جارٍ الفحص…",
  problemFound: "تم العثور على مشكلة",
  needsReview: "تحتاج مراجعة",
  loadingPhotoReview: "جارٍ تحميل مراجعة الصورة…",
  backToPhotoReviews: "العودة إلى مراجعات الصور",
  photoReviewNotFound: "لم يتم العثور على مراجعة الصورة.",
  uploadedPhotos: "الصور المرفوعة",
  shiftDate: "تاريخ الوردية",
  noPhotosUploaded: "لا توجد صور مرفوعة لهذه المهمة.",
  approve: "موافقة",
  reject: "رفض",
  cancel: "إلغاء",
  confirmReject: "تأكيد الرفض",
  rejectReason: "سبب الرفض",
};

const screenCopy: Record<SupportedLocale, ScreenCopy> = { en, nl, pl, uk, pt, ar, fr, es };

export function getScreenCopy(locale: string): ScreenCopy {
  return screenCopy[locale as SupportedLocale] ?? en;
}
