"use client";

import { useEffect, useState } from "react";
import { MdOutlineClose, MdSearch } from "react-icons/md";
import { TbUsers } from "react-icons/tb";
import { assignPlanWorkers, getPlanWorkers, type PlanDetails, type PlanWorkerOption, type WorkerAssignment } from "@/services/actions/cleaningPlans";
import { Select } from "@/components/ui/select";
import { BackendPagination } from "@/components/shared/BackendPagination";
import { TableSkeleton } from "@/components/shared/SkeletonLoader";

const limit = 10;
const positionOptions = [{ value: "teamleader", label: "Team leader" }, { value: "co_leader", label: "Co-leader" }, { value: "normal", label: "Standard worker" }];

export function WorkerAssignmentModal({ planId, planTitle, assignedWorkerIds, onClose, onAssigned }: { planId: string; planTitle: string; assignedWorkerIds: string[]; onClose: () => void; onAssigned: (details: PlanDetails) => void }) {
  const [workers, setWorkers] = useState<PlanWorkerOption[]>([]);
  const [selected, setSelected] = useState<Record<string, WorkerAssignment["position"]>>({});
  const [search, setSearch] = useState(""), [workerType, setWorkerType] = useState("all"), [action, setAction] = useState<"append" | "replace">("append");
  const [page, setPage] = useState(1), [total, setTotal] = useState(0), [planDate, setPlanDate] = useState(""), [timeWindow, setTimeWindow] = useState("");
  const [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState("");

  useEffect(() => { const timer = window.setTimeout(() => { setLoading(true); void getPlanWorkers(planId, { search, workerType, page, limit }).then((result) => { setLoading(false); if (!result.success) return setError(result.error); setError(""); setWorkers(result.data.workers ?? []); setTotal(result.data.total_count ?? 0); setPlanDate(result.data.plan_date ?? ""); setTimeWindow(result.data.plan_time_window ?? ""); }); }, 300); return () => window.clearTimeout(timer); }, [planId, search, workerType, page]);
  useEffect(() => { setPage(1); }, [search, workerType]);

  const toggle = (worker: PlanWorkerOption) => { if (!worker.is_available) return; setSelected((current) => { const next = { ...current }; if (next[worker.worker_id]) delete next[worker.worker_id]; else next[worker.worker_id] = "normal"; return next; }); };
  const submit = async () => { const assignments = Object.entries(selected).map(([worker_id, position]) => ({ worker_id, position })); if (!assignments.length) return setError("Select at least one available worker."); setSaving(true); setError(""); const result = await assignPlanWorkers(planId, assignments, action, true); setSaving(false); if (!result.success) return setError(result.error); onAssigned(result.data); onClose(); };

  return <div onClick={onClose} className="modal-backdrop fixed inset-0 z-[80] flex items-center justify-center p-4"><div onClick={(event) => event.stopPropagation()} className="flex max-h-[92vh] w-full max-w-4xl flex-col rounded-md bg-white shadow-xl">
    <header className="flex items-center gap-3 border-b border-gray-200 px-5 py-4"><span className="flex h-9 w-9 items-center justify-center rounded bg-sky-100 text-sky-600"><TbUsers/></span><div className="min-w-0 flex-1"><h2 className="font-bold text-gray-900">Assign workers</h2><p className="truncate text-xs text-gray-400">{planTitle}{planDate && ` · ${planDate}`}{timeWindow && ` · ${timeWindow}`}</p></div><button onClick={onClose} className="p-1 text-gray-400"><MdOutlineClose className="text-xl"/></button></header>
    <div className="space-y-4 overflow-y-auto p-5">
      <div className="grid gap-3 md:grid-cols-[1fr_180px_180px]"><label className="relative"><MdSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search worker, email or phone..." className="h-10 w-full rounded border border-gray-300 pl-9 pr-3 text-sm outline-none focus:border-sky-500 focus:ring-2 focus:ring-sky-100"/></label><Select value={workerType} onValueChange={setWorkerType} options={[{ value: "all", label: "All worker types" }, { value: "employee", label: "Employees" }, { value: "freelancer", label: "Freelancers" }]}/><Select value={action} onValueChange={(value) => setAction(value as "append" | "replace")} options={[{ value: "append", label: "Append workers" }, { value: "replace", label: "Replace workers" }]}/></div>
      {error && <p className="rounded border border-red-200 bg-red-50 p-3 text-xs font-medium text-red-700">{error}</p>}
      {loading ? <TableSkeleton rows={6} columns={3}/> : <div className="space-y-2">{workers.length === 0 ? <p className="py-12 text-center text-sm text-gray-400">No workers found</p> : workers.map((worker) => { const isSelected = Boolean(selected[worker.worker_id]); const isAssigned = assignedWorkerIds.includes(worker.worker_id); return <div key={worker.worker_id} className={`rounded border p-3 ${!worker.is_available ? "border-red-100 bg-red-50/50" : isSelected ? "border-sky-400 bg-sky-50" : "border-gray-200 bg-white"}`}><div className="flex flex-col gap-3 md:flex-row md:items-center"><label className={`flex min-w-0 flex-1 items-center gap-3 ${worker.is_available ? "cursor-pointer" : "cursor-not-allowed"}`}><input type="checkbox" disabled={!worker.is_available} checked={isSelected} onChange={() => toggle(worker)} className="h-4 w-4 accent-sky-500"/><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-sky-100 text-xs font-bold text-sky-700">{worker.name?.split(" ").map((part) => part[0]).join("").slice(0, 2) || "W"}</span><span className="min-w-0"><span className="flex items-center gap-2"><b className="truncate text-sm text-gray-800">{worker.name}</b>{isAssigned && <span className="rounded bg-indigo-50 px-1.5 py-0.5 text-[10px] font-semibold text-indigo-600">Assigned</span>}</span><span className="block truncate text-xs text-gray-400">{worker.worker_type} · {worker.email || worker.phone}</span></span></label><div className="grid grid-cols-2 gap-3 text-xs md:w-64"><span><b className="block text-gray-700">{worker.formatted_avg_work || "0 mins/day"}</b><span className="text-gray-400">Monthly average</span></span><span><b className="block text-gray-700">{worker.total_shifts_this_month ?? 0}</b><span className="text-gray-400">Shifts this month</span></span></div>{isSelected && <div className="md:w-44"><Select value={selected[worker.worker_id]} onValueChange={(value) => setSelected((current) => ({ ...current, [worker.worker_id]: value as WorkerAssignment["position"] }))} options={positionOptions}/></div>}</div>{!worker.is_available && <p className="mt-2 pl-7 text-xs font-medium text-red-600">Unavailable: {worker.unavailable_reason || "Schedule conflict"}</p>}</div>; })}</div>}
      <BackendPagination page={page} limit={limit} total={total} onPageChange={setPage}/>
    </div>
    <footer className="flex items-center justify-between gap-3 border-t border-gray-200 px-5 py-4"><p className="text-xs text-gray-500">{Object.keys(selected).length} worker(s) selected</p><div className="flex gap-2"><button onClick={onClose} className="rounded border border-gray-300 px-4 py-2 text-sm">Cancel</button><button onClick={() => void submit()} disabled={saving || !Object.keys(selected).length} className="rounded bg-sky-500 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Assigning..." : action === "replace" ? "Replace workers" : "Assign workers"}</button></div></footer>
  </div></div>;
}
