import { authenticated } from "./auth";
import type { ShiftDraftInput, ShiftApi } from "./shifts";
const json = (value: unknown) => ({ headers: { "Content-Type": "application/json" }, body: JSON.stringify(value) });
export type RosterShift = { shift_id: string; client_id: string; client_name: string; location_id: string; location_name: string; start_time: string; end_time: string; duration_hours: number; status: string; shift_notes?: string; rooms_count?: number };
export async function getRosterShift(shiftId: string) { return authenticated<{ shift_id: string; worker_id: string; worker_name: string; worker_profile_photo: string; assignment_label: string; location_id: string; location_name: string; location_address: string; start_time: string; end_time: string; time_range: string; date: string; client_id: string; client_name: string; status: string }>(`/manager/roster/shifts/${encodeURIComponent(shiftId)}`, { method: "GET" }); }
export async function deleteRosterShift(shiftId: string) { return authenticated<string>(`/manager/roster/shifts/${encodeURIComponent(shiftId)}`, { method: "DELETE" }); }
export async function createRosterDraft(input: ShiftDraftInput) { return authenticated<ShiftApi>("/manager/roster/drafts", { method: "POST", ...json(input) }); }
export async function assignRosterShift(input: { draft_id: string; team_leader_id: string; worker_ids: string[]; worker_assignments: Array<{ worker_id: string; shift_role: string }> }) { return authenticated<ShiftApi>("/manager/roster/shifts/assign", { method: "POST", ...json(input) }); }
export async function getRosterClients(search?: string) { return authenticated<unknown>(`/manager/roster/dropdowns/clients${search ? `?search=${encodeURIComponent(search)}` : ""}`, { method: "GET" }); }
export async function getRosterLocations(clientId?: string, search?: string) { const q = new URLSearchParams({ page: "1", limit: "100" }); if (clientId) q.set("client_id", clientId); if (search) q.set("search", search); return authenticated<{ locations: unknown[] }>(`/manager/roster/dropdowns/locations?${q}`, { method: "GET" }); }
export async function getRosterWorkers(input: { workerType?: string; status?: string; search?: string; targetDate?: string } = {}) { const q = new URLSearchParams({ page: "1", limit: "100" }); Object.entries({ worker_type: input.workerType, status_filter: input.status, search: input.search, target_date: input.targetDate }).forEach(([key, value]) => { if (value) q.set(key, value); }); return authenticated<{ workers: unknown[] }>(`/manager/roster/dropdowns/workers?${q}`, { method: "GET" }); }
