"use server";
import { authenticated } from "./auth";
export type WorkerApi = { worker_id: string; full_name: string; profile_photo: string; worker_type: string; position: string; location: string; languages: string[]; hours_worked: string; hours_worked_numeric: number; status: string; account_status: string; approval_status: string; is_active: boolean };
export type WorkerInput = { full_name: string; name?: string; email: string; phone: string; worker_type: string; position: string; base_location: string; hourly_rate?: number; languages: string[]; status: string; national_id: string; certificates: string[]; national_id_front?: string; national_id_back?: string; employee_contract_pdf?: string };

const json = (value: unknown) => ({ headers: { "Content-Type": "application/json" }, body: JSON.stringify(value) });
const params = (page: number, limit: number, search?: string, workerType?: string, status?: string) => { const q = new URLSearchParams({ page: String(page), limit: String(limit) }); if (search) q.set("search", search); if (workerType) q.set("worker_type", workerType); if (status) q.set("status_filter", status); return q; };
export async function getWorkers(input: { page?: number; limit?: number; search?: string; workerType?: string; status?: string } = {}) { return authenticated<{ total_workers: number; employees_count: number; freelancers_count: number; page: number; limit: number; has_more: boolean; workers: WorkerApi[] }>(`/manager/workers?${params(input.page ?? 1, input.limit ?? 100, input.search, input.workerType, input.status)}`, { method: "GET" }); }
export async function createWorker(input: WorkerInput) { return authenticated<WorkerApi>("/manager/workers", { method: "POST", ...json(input) }); }
export async function updateWorkerStatus(workerId: string, status: string, reason: string) { return authenticated<string>(`/manager/workers/${encodeURIComponent(workerId)}/status`, { method: "PATCH", ...json({ status, reason }) }); }
export async function deleteWorker(workerId: string) { return authenticated<string>(`/manager/workers/${encodeURIComponent(workerId)}`, { method: "DELETE" }); }
export async function getDeletedWorkers(page = 1, limit = 10, search?: string) { return authenticated<{ total_workers: number; employees_count: number; freelancers_count: number; workers: WorkerApi[] }>(`/manager/workers/deleted-list?${params(page, limit, search)}`, { method: "GET" }); }
export async function restoreWorker(workerId: string) { return authenticated<string>(`/manager/workers/${encodeURIComponent(workerId)}/restore`, { method: "POST" }); }
export async function getWorkerImportTemplate() { return authenticated<string>("/manager/workers/bulk-import/template", { method: "GET" }); }
export async function importWorkers(file: File) { const data = new FormData(); data.append("file", file); return authenticated<{ total_rows: number; imported_count: number; failed_count: number; errors: string[] }>("/manager/workers/bulk-import", { method: "POST", body: data }); }
export async function exportWorkers(workerType?: string) { return authenticated<string>(`/manager/workers/export${workerType ? `?worker_type=${encodeURIComponent(workerType)}` : ""}`, { method: "GET" }); }
export async function getWorkerApprovals(page = 1, limit = 10, status = "pending", search?: string) { const q = new URLSearchParams({ page: String(page), limit: String(limit), status_filter: status }); if (search) q.set("search", search); return authenticated<{ total_count: number; pending_approvals: unknown[] }>(`/manager/worker-approvals?${q}`, { method: "GET" }); }
export async function approveWorker(workerId: string, input: { worker_type: string; position: string; base_location: string }) { return authenticated<unknown>(`/manager/workers/${encodeURIComponent(workerId)}/approve`, { method: "POST", ...json(input) }); }
export async function rejectWorker(workerId: string, reason: string) { return authenticated<string>(`/manager/workers/${encodeURIComponent(workerId)}/reject`, { method: "POST", ...json({ reject_reason: reason }) }); }
export async function getAvailableWorkers(page = 1, limit = 100, search?: string) { const q = new URLSearchParams({ page: String(page), limit: String(limit) }); if (search) q.set("search", search); return authenticated<{ total_count: number; workers: unknown[] }>(`/manager/workers-list?${q}`, { method: "GET" }); }
